# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: '3'
services:
  chrome:
    image: selenium/standalone-chrome:3.141.59-20210607
    ports:
      - "4444:4444"
    shm_size: '2gb'
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
      - NODE_MAX_INSTANCES=5 
      - NODE_MAX_SESSION=5
networks:
    default:
        external: true
        name: bi-docker-stack_upstream
      